### ISSUE TITLE
singularize("pies") yields "py" instead of "pie"

### ISSUE THREAD

**Issue by edoardofelici** [martinandert/inflected#11]
when attempting to singularize the word "pie", "pies" is correctly returned
but reversing "pies" to singular gives "py" instead of pie.

**Comment by martinandert** [comment]
Please use the `inflections` module to add a rule for this special case. Example:

```js
Inflector.inflections('en', (inflect) => {
  inflect.singular(/^(pie)s/i, '$1');
});
```

See also [defaults.js](https://github.com/martinandert/inflected/blob/master/src/defaults.js).
